### ISSUE TITLE
Initialize Front End React App

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/EthGlobal-West-Texas-Oil#10]
**Is your feature request related to a problem? Please describe.**
We currently don't have a react app/front end initialized.

**Describe the solution you'd like**

Use npm to install react and then initialize react app project. 

**Describe alternatives you've considered**

You can also use npx, yarn.

**Comment by KenMan79** [comment]
The front end had been initialized with React Installed and the use of yarn with Rimble added to the PR awaiting approval. Please assign tasks to me. PR's are  #11 and #18

**Comment by KenMan79** [comment]
Thank you

**Comment by KenMan79** [comment]
thanks
