### ISSUE TITLE
Implement the dBOL asset on the blockchain

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/EthGlobal-West-Texas-Oil#12]
**Is your feature request related to a problem? Please describe.**

When a BOL is delivered to the offloading specialist, payment should occur immediately.

**Describe the solution you'd like**

We should utilize ERC998 to create a dBOL NFT which will control aTokens. The aTokens and the dBOL should not be able to be accessed by anyone except upon delivery, in which case it will be given to the driver who can do with the assets as they wish. 

**Describe alternatives you've considered**

We could use the ERC1155 to create a multi-token contract which manages both the BOL and dBOL.

**Additional context**

aTokens are interest bearing and the balance continually increases. When we have a ERC998, we should make sure to keep track of the interest each dBOL is accrueing, especially if our contract is managing multiple.

**Comment by skellet0r** [comment]
Integration with AAVE to earn interest on deposited stable coins.
After the BOL makes it to the destination, this should be distributed to the trucker.

Main reason to have a dBOL is that the driver should not have access to the funds until after they've completed their delivery, at which point they will get paid.

**Comment by ermz** [comment]
I'll take this ticket.

**Comment by skellet0r** [comment]
@ermz awesome initiative!

**Comment by skellet0r** [comment]
Resolved via #41
