### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/EthGlobal-West-Texas-Oil#13]
**Is your feature request related to a problem? Please describe.**

Users can't switch between different pages without some form of navigation bar/panel.

**Describe the solution you'd like**

There should be a simple nav bar that users can click to move between pages.

**Describe alternatives you've considered**

We could have different url routes, but to keep this a simple single page web app, we can use routing + a nav component.

**Additional context**

Depending on the access permissions of the user, there will be different options available on the navigation bar.

**Comment by andykeh710** [comment]
Ok I'm gonna try to make this with some blank templates for the pages. Might need help :/

**Comment by andykeh710** [comment]
We are downgrading to a CRUD app with just a couple of pages this isn't needed anymore
