### ISSUE TITLE
Initialize Truffle Project

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/EthGlobal-West-Texas-Oil#16]
**Is your feature request related to a problem? Please describe.**

There is no truffle project currently!

**Describe the solution you'd like**

A truffle project should be initialized.

**Describe alternatives you've considered**

Alternatives to truffle (javascript) include, hardhat (typescript) and brownie (python)

**Comment by ermz** [comment]
Good point. I think we have to see what everyone is most comfortable with. I'm more comfortable with truffle(javascript), but I'm willing to learn hardhat or brownie.

**Comment by skellet0r** [comment]
Awesome I'll start us on a truffle project @ermz

**Comment by KenMan79** [comment]
That's a great idea since most have experience with javascript.
