### ISSUE TITLE
The Readme is lacking content

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/EthGlobal-West-Texas-Oil#19]
**Is your feature request related to a problem? Please describe.**

Nobody knows what this project is about, maybe we should add something to the README?

**Comment by andykeh710** [comment]
I'm gonna add to this for practice rn.

**Comment by skellet0r** [comment]
@andykeh710 woohoo!!!! :+1:

**Comment by KenMan79** [comment]
Sounda great @andykeh710
