### ISSUE TITLE
CRUD app / main page 

### ISSUE THREAD

**Issue by andykeh710** [EthBuilders/EthGlobal-West-Texas-Oil#38]
**Is your feature request related to a problem? Please describe.**
The BOL has no way of being created and uploaded. 

**Describe the solution you'd like**
Build a CRUD app using react to handle the BOL.

**Describe alternatives you've considered**
Using something other than react(e.g. vue) Using raw HTML

**Comment by andykeh710** [comment]
Ima do this. gonna try to have this knocked out today. I am taking a day off work on Tues/wed to wrap anything up as well

**Comment by KenMan79** [comment]
approve

**Comment by skellet0r** [comment]
Resolved via #39
